version: "3.9"

services:
  
  mongodb:
    hostname: mongodb
    image : mongo
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all"]
    container_name: mongodb
    volumes:
    - ./mongo/:/data/db
    ports:
    - 27017:27017
    restart: unless-stopped
    networks:
      - docker-stack 

  spark:
    container_name: spark
    build: ./spark
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - 8080:8080
      - 7077:7077
      - 4041:4041
    networks:
      - docker-stack

  pyspark-notebook:
    container_name: notebook
    build:
      context: ./spark/
      dockerfile: Dockerfile-notebook
    working_dir: /home/$USER/work
    user: root
    ports:
      - 8888:8888
    volumes:
       - $HOME_NB_SPARK:/home/$USER/work
    environment:
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
      - NB_USER=${USER}
      - CHOWN_HOME=yes
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
      - NB_UID=1000
      - NB_GID=100
      - NB_GROUP=staff
    networks:
      - docker-stack

  minio:
    hostname: minio
    image: 'minio/minio:RELEASE.2021-01-08T21-18-21Z'
    container_name: minio
    ports:
      - '9000:9000'
    volumes:
      - ./minio-data:/data
    environment:
      MINIO_ACCESS_KEY: ${ACCESS_KEY}
      MINIO_SECRET_KEY: ${SECRET_KEY}
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - docker-stack

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    networks:
      - docker-stack  
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:${MINIO_PORT} ${ACCESS_KEY} ${SECRET_KEY};
      /usr/bin/mc mb myminio/${DATA_REPO_BUCKET_NAME};
      /usr/bin/mc policy set public myminio/${DATA_REPO_BUCKET_NAME};
      exit 0;
      "
  
 
networks:
  docker-stack:      